-- PythonInLua: Python 3.13 opcode definitions
-- Generated from CPython 3.13.5 opcode table

local M = {}

-- Opcode name-to-number mapping
M.opmap = {
    CACHE                       = 0,
    BEFORE_ASYNC_WITH           = 1,
    BEFORE_WITH                 = 2,
    BINARY_SLICE                = 4,
    BINARY_SUBSCR               = 5,
    CHECK_EG_MATCH              = 6,
    CHECK_EXC_MATCH             = 7,
    CLEANUP_THROW               = 8,
    DELETE_SUBSCR               = 9,
    END_ASYNC_FOR               = 10,
    END_FOR                     = 11,
    END_SEND                    = 12,
    EXIT_INIT_CHECK             = 13,
    FORMAT_SIMPLE               = 14,
    FORMAT_WITH_SPEC            = 15,
    GET_AITER                   = 16,
    RESERVED                    = 17,
    GET_ANEXT                   = 18,
    GET_ITER                    = 19,
    GET_LEN                     = 20,
    GET_YIELD_FROM_ITER         = 21,
    INTERPRETER_EXIT            = 22,
    LOAD_ASSERTION_ERROR        = 23,
    LOAD_BUILD_CLASS            = 24,
    LOAD_LOCALS                 = 25,
    MAKE_FUNCTION               = 26,
    MATCH_KEYS                  = 27,
    MATCH_MAPPING               = 28,
    MATCH_SEQUENCE              = 29,
    NOP                         = 30,
    POP_EXCEPT                  = 31,
    POP_TOP                     = 32,
    PUSH_EXC_INFO               = 33,
    PUSH_NULL                   = 34,
    RETURN_GENERATOR            = 35,
    RETURN_VALUE                = 36,
    SETUP_ANNOTATIONS           = 37,
    STORE_SLICE                 = 38,
    STORE_SUBSCR                = 39,
    TO_BOOL                     = 40,
    UNARY_INVERT                = 41,
    UNARY_NEGATIVE              = 42,
    UNARY_NOT                   = 43,
    WITH_EXCEPT_START           = 44,
    BINARY_OP                   = 45,
    BUILD_CONST_KEY_MAP         = 46,
    BUILD_LIST                  = 47,
    BUILD_MAP                   = 48,
    BUILD_SET                   = 49,
    BUILD_SLICE                 = 50,
    BUILD_STRING                = 51,
    BUILD_TUPLE                 = 52,
    CALL                        = 53,
    CALL_FUNCTION_EX            = 54,
    CALL_INTRINSIC_1            = 55,
    CALL_INTRINSIC_2            = 56,
    CALL_KW                     = 57,
    COMPARE_OP                  = 58,
    CONTAINS_OP                 = 59,
    CONVERT_VALUE               = 60,
    COPY                        = 61,
    COPY_FREE_VARS              = 62,
    DELETE_ATTR                 = 63,
    DELETE_DEREF                = 64,
    DELETE_FAST                 = 65,
    DELETE_GLOBAL               = 66,
    DELETE_NAME                 = 67,
    DICT_MERGE                  = 68,
    DICT_UPDATE                 = 69,
    ENTER_EXECUTOR              = 70,
    EXTENDED_ARG                = 71,
    FOR_ITER                    = 72,
    GET_AWAITABLE               = 73,
    IMPORT_FROM                 = 74,
    IMPORT_NAME                 = 75,
    IS_OP                       = 76,
    JUMP_BACKWARD               = 77,
    JUMP_BACKWARD_NO_INTERRUPT  = 78,
    JUMP_FORWARD                = 79,
    LIST_APPEND                 = 80,
    LIST_EXTEND                 = 81,
    LOAD_ATTR                   = 82,
    LOAD_CONST                  = 83,
    LOAD_DEREF                  = 84,
    LOAD_FAST                   = 85,
    LOAD_FAST_AND_CLEAR         = 86,
    LOAD_FAST_CHECK             = 87,
    LOAD_FAST_LOAD_FAST         = 88,
    LOAD_FROM_DICT_OR_DEREF     = 89,
    LOAD_FROM_DICT_OR_GLOBALS   = 90,
    LOAD_GLOBAL                 = 91,
    LOAD_NAME                   = 92,
    LOAD_SUPER_ATTR             = 93,
    MAKE_CELL                   = 94,
    MAP_ADD                     = 95,
    MATCH_CLASS                 = 96,
    POP_JUMP_IF_FALSE           = 97,
    POP_JUMP_IF_NONE            = 98,
    POP_JUMP_IF_NOT_NONE        = 99,
    POP_JUMP_IF_TRUE            = 100,
    RAISE_VARARGS               = 101,
    RERAISE                     = 102,
    RETURN_CONST                = 103,
    SEND                        = 104,
    SET_ADD                     = 105,
    SET_FUNCTION_ATTRIBUTE      = 106,
    SET_UPDATE                  = 107,
    STORE_ATTR                  = 108,
    STORE_DEREF                 = 109,
    STORE_FAST                  = 110,
    STORE_FAST_LOAD_FAST        = 111,
    STORE_FAST_STORE_FAST       = 112,
    STORE_GLOBAL                = 113,
    STORE_NAME                  = 114,
    SWAP                        = 115,
    UNPACK_EX                   = 116,
    UNPACK_SEQUENCE             = 117,
    YIELD_VALUE                 = 118,
    RESUME                      = 149,
}

-- Reverse mapping: number -> name
M.opname = {}
for name, num in pairs(M.opmap) do
    M.opname[num] = name
end

-- Number of CACHE entries that follow each opcode.
-- In Python 3.13, CALL is followed by 3 CACHE words, etc.
-- Only opcodes with nonzero cache are listed here.
M.cache_count = {
    [M.opmap.BINARY_SUBSCR]         = 1,
    [M.opmap.STORE_SUBSCR]          = 1,
    [M.opmap.BINARY_OP]             = 1,
    [M.opmap.UNPACK_SEQUENCE]       = 1,
    [M.opmap.STORE_ATTR]            = 4,
    [M.opmap.LOAD_ATTR]             = 9,
    [M.opmap.COMPARE_OP]            = 1,
    [M.opmap.CONTAINS_OP]           = 1,
    [M.opmap.LOAD_GLOBAL]           = 4,
    [M.opmap.LOAD_SUPER_ATTR]       = 1,
    [M.opmap.CALL]                  = 3,
    [M.opmap.CALL_KW]               = 3,
    [M.opmap.FOR_ITER]              = 1,
    [M.opmap.SEND]                  = 1,
    [M.opmap.TO_BOOL]               = 3,
    [M.opmap.POP_JUMP_IF_FALSE]     = 1,
    [M.opmap.POP_JUMP_IF_TRUE]      = 1,
    [M.opmap.POP_JUMP_IF_NONE]      = 1,
    [M.opmap.POP_JUMP_IF_NOT_NONE]  = 1,
    [M.opmap.JUMP_BACKWARD]         = 1,
}

return M
